name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: action/checkout@2

      - name: Set up Python 3.6
        uses: action/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Run test
        run: |
          pytest tests
